# Generated by Django 5.1.7 on 2025-04-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilchangerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilchangerecord',
            name='kilometrage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilchangerecord',
            name='next_reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
