# Generated by Django 5.1.7 on 2025-04-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_oilchangerecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
